# Generated by Django 3.0 on 2020-03-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200309_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gives',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='receives',
            field=models.CharField(max_length=10),
        ),
    ]
