# Generated by Django 3.0 on 2020-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200309_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.zipCode'),
        ),
    ]
