# Generated by Django 3.0 on 2020-03-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donor_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.country'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.state'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zipcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.zipCode'),
        ),
    ]
