# Generated by Django 3.0 on 2020-03-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200309_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gives',
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zipcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zipCode'),
        ),
    ]
