# Generated by Django 3.0 on 2020-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200309_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='urgent_available',
            field=models.BooleanField(default=False),
        ),
    ]
