# Generated by Django 3.0 on 2020-03-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donor_urgent_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
