# Generated by Django 3.0 on 2020-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200310_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
