# Generated by Django 3.0 on 2020-03-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_donor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zipCode'),
        ),
    ]
